# Generated by Django 4.1.3 on 2023-02-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('sarlavha', models.CharField(max_length=40)),
                ('video', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=40)),
                ('sana', models.DateField()),
                ('matn', models.TextField()),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
    ]
